/** Seed rows for Universities list (matches screenshot). */
export const INITIAL_ORGANIZATION_ROWS = [
  {
    id: 'org-qarshi-davlat',
    name: 'Qarshi davlat universiteti',
    entityCount: 2,
    quotaUsed: 23,
    quotaTotal: 25,
    active: true,
    region: 'south',
    category: 'services',
  },
  {
    id: 'org-tashkent-state',
    name: 'Tashkent State University',
    entityCount: 12,
    quotaUsed: 23,
    quotaTotal: 25,
    active: true,
    region: 'south',
    category: 'services',
  },
  {
    id: 'org-samarkand-state',
    name: 'Samarkand State University',
    entityCount: 12,
    quotaUsed: 23,
    quotaTotal: 25,
    active: true,
    region: 'south',
    category: 'services',
  },
  {
    id: 'org-bukhara-state',
    name: 'Bukhara State University',
    entityCount: 12,
    quotaUsed: 23,
    quotaTotal: 25,
    active: true,
    region: 'south',
    category: 'services',
  },
  {
    id: 'org-andijan-state',
    name: 'Andijan State University',
    entityCount: 12,
    quotaUsed: 23,
    quotaTotal: 25,
    active: true,
    region: 'south',
    category: 'services',
  },
  {
    id: 'org-nukus-ped',
    name: 'Nukus State Pedagogical Institute',
    entityCount: 12,
    quotaUsed: 23,
    quotaTotal: 25,
    active: true,
    region: 'south',
    category: 'services',
  },
  {
    id: 'org-fergana-state',
    name: 'Fergana State University',
    entityCount: 12,
    quotaUsed: 23,
    quotaTotal: 25,
    active: true,
    region: 'south',
    category: 'services',
  },
  {
    id: 'org-namangan-state',
    name: 'Namangan State University',
    entityCount: 12,
    quotaUsed: 23,
    quotaTotal: 25,
    active: true,
    region: 'south',
    category: 'services',
  },
  {
    id: 'org-karshi-eei',
    name: 'Karshi Engineering-Economic Institute',
    entityCount: 12,
    quotaUsed: 23,
    quotaTotal: 25,
    active: true,
    region: 'north',
    category: 'services',
  },
  {
    id: 'org-tuit',
    name: 'Tashkent University of Information Technologies',
    entityCount: 12,
    quotaUsed: 23,
    quotaTotal: 25,
    active: true,
    region: 'north',
    category: 'services',
  },
  {
    id: 'org-world-languages',
    name: 'Uzbek State University of World Languages',
    entityCount: 12,
    quotaUsed: 23,
    quotaTotal: 25,
    active: true,
    region: 'north',
    category: 'services',
  },
  {
    id: 'org-tashkent-medical',
    name: 'Tashkent Medical Academy',
    entityCount: 12,
    quotaUsed: 23,
    quotaTotal: 25,
    active: true,
    region: 'north',
    category: 'services',
  },
  {
    id: 'org-arts-culture',
    name: 'Uzbekistan State Institute of Arts and Culture',
    entityCount: 12,
    quotaUsed: 23,
    quotaTotal: 25,
    active: true,
    region: 'north',
    category: 'services',
  },
];
